
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muhammad Izzuddin
 */
public class client extends javax.swing.JFrame {

    private Socket server = null;
    private BufferedOutputStream bos = null;
    private BufferedInputStream bis = null;
    private ObjectOutputStream oos  = null;
    private ObjectInputStream ois  = null;
    private FileInputStream fis = null;
    private FileOutputStream fos = null;
    private String destination = "d:/";
    private File f;
    private ArrayList<String> rcpt = new ArrayList<>();
    /**
     * Creates new form client
     */
    public client() {
        initComponents();
        this.setEnabling(false);
    }
    private void setEnabling(boolean param){
        rcptList.setEnabled(param);
        sRcptList.setEnabled(param); 
        pathFile.setEnabled(param);
        rfshBtn.setEnabled(param);
        addBtn.setEnabled(param);
        sendFile.setEnabled(param);
        attachBtn.setEnabled(param);
        inbox.setEnabled(param);
        rtrvBtn.setEnabled(param);
        rfshInbox.setEnabled(param);
        rtrvBtn.setEnabled(param);
        clrBtn.setEnabled(param);
        disConn.setEnabled(param);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        conn = new javax.swing.JButton();
        attachBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sRcptList = new javax.swing.JTextArea();
        pathFile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uname = new java.awt.TextField();
        sendFile = new javax.swing.JButton();
        label1 = new java.awt.Label();
        disConn = new javax.swing.JButton();
        rcptList = new javax.swing.JComboBox();
        addBtn = new javax.swing.JButton();
        rfshBtn = new javax.swing.JButton();
        clrBtn = new javax.swing.JButton();
        rtrvBtn = new javax.swing.JButton();
        inbox = new javax.swing.JComboBox();
        rfshInbox = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Recipient List");

        jLabel2.setText("Username :");

        conn.setText("Connect");
        conn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connActionPerformed(evt);
            }
        });

        attachBtn.setText("attach");
        attachBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachBtnActionPerformed(evt);
            }
        });

        sRcptList.setEditable(false);
        sRcptList.setColumns(12);
        sRcptList.setRows(5);
        sRcptList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(sRcptList);

        pathFile.setEditable(false);

        jLabel3.setText("Path of file :");

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        sendFile.setText("SEND");
        sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("SIMPLE FILE SHARING");

        disConn.setText("Disconnect");
        disConn.setEnabled(false);
        disConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disConnActionPerformed(evt);
            }
        });

        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        rfshBtn.setText("refresh");
        rfshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfshBtnActionPerformed(evt);
            }
        });

        clrBtn.setText("clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        rtrvBtn.setText("Retrieve");
        rtrvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtrvBtnActionPerformed(evt);
            }
        });

        rfshInbox.setText("Refresh");
        rfshInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfshInboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Inbox File List");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rcptList, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(conn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathFile, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rfshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(sendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(attachBtn))
                                    .addComponent(disConn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rtrvBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(inbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(rfshInbox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rcptList, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(rfshBtn)
                    .addComponent(sendFile)
                    .addComponent(attachBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rtrvBtn)
                            .addComponent(rfshInbox))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clrBtn)
                    .addComponent(disConn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connActionPerformed
        try {
            if (uname.getText().equals("")){
                throw new Exception("Silahkan isi username terlebih dahulu",null);
            }
            server = new Socket("localhost",6060);
            bos = new BufferedOutputStream(server.getOutputStream());
            oos = new ObjectOutputStream(server.getOutputStream());
            ois = new ObjectInputStream(server.getInputStream());
            conn.setEnabled(false);
            uname.setEnabled(false);
            disConn.setEnabled(true);
            this.setEnabling(true);
            oos.writeUTF(uname.getText());
            oos.flush();
            
            String msg;
            msg = ois.readUTF();
            File file = new File("D:/" + uname.getText());
            if (!file.exists()) {
                if (file.mkdir()) {
                        System.out.println("Directory is created!");
                } else {
                        System.out.println("Failed to create directory!");
                }
            }
            System.out.println(msg);
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Server sedang offline");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_connActionPerformed

    private void attachBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachBtnActionPerformed
        JFileChooser jc = new JFileChooser();
        jc.showOpenDialog(null);
        f = jc.getSelectedFile();
        if (f != null)
            pathFile.setText(f.getAbsolutePath());
    }//GEN-LAST:event_attachBtnActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileActionPerformed
        try {
            if (f == null || rcpt.isEmpty()){
                throw new Exception("Pastikan Anda Sudah Memilih File dan Memilih Recipient",null);
            }
            oos.writeUTF("RCPT");
            oos.flush();
            
            String msg = ois.readUTF();
            if (msg.equals("OK")){
                ListString Baru = new ListString();
                Baru.setNames(rcpt);
                oos.writeObject(Baru);
                oos.flush();
                oos.reset();
            }
            msg = ois.readUTF();
            if (msg.equals("FILE")){
                ContentFile MyFile = new ContentFile(((int)f.length()));
                MyFile.setNamafile(f.getName());
                MyFile.setUkuran((int)f.length());
                byte [] mybyte = new byte[(int)f.length()];
                fis = new FileInputStream(f);
                bis = new BufferedInputStream(fis);
                bis.read(mybyte,0,mybyte.length);
                MyFile.setByteFile(mybyte);
                System.out.print(MyFile.getUkuran());
                
                oos.writeObject(MyFile);
                oos.flush();
                oos.reset();
                bis.close();
                fis.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_sendFileActionPerformed

    private void disConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disConnActionPerformed
        try {
            oos.writeUTF("QUIT");
            oos.flush();
            server.close();
            this.setEnabling(false);
            conn.setEnabled(true);
            uname.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_disConnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try{
            if (rcptList.getSelectedItem() == null)
                throw new Exception("Silahkan pilih recipient terlebih dahulu",null);
            sRcptList.append(rcptList.getSelectedItem().toString() + "\n");
            rcpt.add(rcptList.getSelectedItem().toString());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void rfshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfshBtnActionPerformed
        try {
            oos.writeUTF("LIST");
            oos.flush();
            ListString Baru = new ListString();
            Baru = (ListString) ois.readObject();
            ArrayList<String> names = Baru.getNames();
            rcptList.removeAllItems();
            for (int i = 0; i < names.size();i++){
                rcptList.addItem(names.get(i));
            }
        } catch (IOException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rfshBtnActionPerformed

    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        sRcptList.setText(null);
        rcpt.clear();
    }//GEN-LAST:event_clrBtnActionPerformed

    private void rtrvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtrvBtnActionPerformed
        ContentFile MyFile;
        try {
            if (inbox.getSelectedItem()== null)
                throw new Exception("Anda belum memilih file yang akan di download",null);
            oos.writeUTF("RETR");
            oos.flush();
            String msg = ois.readUTF();
            if (msg.equals("OK")){
                oos.writeUTF(inbox.getSelectedItem().toString());
                oos.flush();
                MyFile = (ContentFile) ois.readObject();
                System.out.println(MyFile.getNamafile());
                byte [] mybytearray  = new byte [MyFile.getUkuran()+30000];
                System.out.println(MyFile.getUkuran());
                mybytearray = MyFile.getByteFile();
                File f = new File(destination + "/" + uname.getText() + "/" + MyFile.getNamafile());
                int i = 0;
                while (f.exists() == true){
                    i++;
                    f = new File(destination + "/" + uname.getText() + "/" + i + "_" + MyFile.getNamafile());
                    System.out.println(i);
                }
                if (i==0)
                    destination += "/" + uname.getText() + "/" + MyFile.getNamafile();
                else 
                    destination += "/" + uname.getText() + "/" + i + "_" + MyFile.getNamafile();
                fos = new FileOutputStream(destination);
                bos = new BufferedOutputStream(fos);
                bos.write(mybytearray, 0 , MyFile.getUkuran());
                bos.flush();
                destination = "d:/";
                bos.close();
                fos.close();
                inbox.removeItem(inbox.getSelectedItem());
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_rtrvBtnActionPerformed

    private void rfshInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfshInboxActionPerformed
        try {
            oos.writeUTF("INBOX");
            oos.flush();
            ListString Baru = new ListString();
            Baru = (ListString) ois.readObject();
            ArrayList<String> names = Baru.getNames();
            inbox.removeAllItems();
            for (int i = 0; i < names.size();i++){
                inbox.addItem(names.get(i));
            }
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rfshInboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton attachBtn;
    private javax.swing.JButton clrBtn;
    private javax.swing.JButton conn;
    private javax.swing.JButton disConn;
    private javax.swing.JComboBox inbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTextField pathFile;
    private javax.swing.JComboBox rcptList;
    private javax.swing.JButton rfshBtn;
    private javax.swing.JButton rfshInbox;
    private javax.swing.JButton rtrvBtn;
    private javax.swing.JTextArea sRcptList;
    private javax.swing.JButton sendFile;
    private java.awt.TextField uname;
    // End of variables declaration//GEN-END:variables
}
